services:
  - type: web
    name: group-diary-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://fe-lilac-three.vercel.app
      - key: PORT
        value: 10000
